version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "venus/quantum"
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "venus/theswitch"
    environment:
      VEGA_WEB_SERVER_URL: "http://localhost:8000"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
