version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "venus/quantum"
    network_mode: "host"
    environment:
      API_URL: "http://localhost:8080"
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "venus/theswitch"
    network_mode: "host"
    environment:
      API_URL: "http://localhost:8000"


